baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Asif Islam - Personal Website'
theme = 'ananke'

enableRobotsTXT = true


[params]
  text_color = "black"
  author = "Asif Islam"
  favicon = ""
  site_logo = ""
  description = "Aspring Developer and Statician"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  recent_posts_number = 5

[[params.ananke_socials]]
    name = "github"
    url = "https://github.com/asif4318"

[[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/asif-islam-ufl/"